services:
  postgres_test:
    container_name: postgres-sql-cookit-test
    image: postgres
    env_file:
      - .env.test
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: cookit_test
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - cookit_test
    restart: unless-stopped
  mail-dev_test:
    container_name: mail-dev-cookit-test
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  cookit_test:
    driver: bridge

volumes:
  postgres:
    driver: local