spring:
  datasource:
    url: ${env.POSTGRES_URL}
    username: ${env.POSTGRES_USER}
    password: ${env.POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: ${env.MAIL_USERNAME}
    password: ${env.MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

application:
  security:
    jwt:
      secret-key: ${env.JWT_SECRET_KEY}
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photo-output-path: ./uploads

server:
  port: 8088
  servlet:
    context-path: /api/v1